
project_id = "wmclujwtwuzscfqbzfxf"

[auth]
enable_confirmations = false
enable_passwordless = true

# Disable Row Level Security (RLS) globally for this project
[postgres_config]
anon_role = "anon"

# Explicitly disable RLS for specific tables
[[postgres_config.tables]]
name = "campaigns"
rls_enabled = false

[[postgres_config.tables]]
name = "actual_budgets"
rls_enabled = false

[[postgres_config.tables]]
name = "profiles"
rls_enabled = false

# Configuration for the backup function
[functions.backup-campaigns]
verify_jwt = false
