
project_id = "wmclujwtwuzscfqbzfxf"

[auth]
enable_confirmations = false
enable_passwordless = true

# Disable Row Level Security (RLS) for the campaigns table
[postgres_config]
anon_role = "anon"

# This explicitly disables RLS for the campaigns table by name
[[postgres_config.tables]]
name = "campaigns"
rls_enabled = false
