
project_id = "wmclujwtwuzscfqbzfxf"

[auth]
enable_confirmations = false
enable_passwordless = true

# Disable RLS enforcement for campaigns table to allow any user to perform operations
[auth.policies]
disable_rls_for_campaigns = true
